### ISSUE TITLE
Return value must be of type Spatie\RouteTesting\RouteTesting, Pest\PendingCalls\TestCall returned

### ISSUE THREAD

**Issue by pratikkuikel** [spatie/pest-plugin-route-testing#7]
# Steps to reproduce
1. Make sure pest is installed.
2. Composer require spatie/pest-plugin-route-testing
3. Create a new file : RouteTest.php in tests/Feature directory.
4. Write the code 
```php
<?php

use function Spatie\RouteTesting\routeTesting;

routeTesting('all routes')
    ->assertSuccessful();
```
5. Run php artisan test
6. See the error 
```php
   ERROR  Spatie\RouteTesting\routeTesting(): Return value must be of type Spatie\RouteTesting\RouteTesting, Pest\PendingCalls\TestCall returned

   Location: \vendor\spatie\pest-plugin-route-testing\src\Autoload.php:16

   #0 \tests\Feature\RouteTest.php(5): Spatie\RouteTesting\routeTesting('all routes')
   #1 \vendor\pestphp\pest\overrides\Runner\TestSuiteLoader.php(89): include_once('C:\\Users\\prati\\...')
   #2 \vendor\pestphp\pest\overrides\Runner\TestSuiteLoader.php(92): PHPUnit\Runner\TestSuiteLoader::PHPUnit\Runner\{closure}()
   #3 \vendor\phpunit\phpunit\src\Framework\TestSuite.php(253): PHPUnit\Runner\TestSuiteLoader->load('C:\\Users\\prati\\...')
   #4 \vendor\phpunit\phpunit\src\Framework\TestSuite.php(270): PHPUnit\Framework\TestSuite->addTestFile('C:\\Users\\prati\\...')
   #5 \vendor\phpunit\phpunit\src\TextUI\Configuration\Xml\TestSuiteMapper.php(100): PHPUnit\Framework\TestSuite->addTestFiles(Array)
   #6 \vendor\phpunit\phpunit\src\TextUI\Configuration\TestSuiteBuilder.php(72): PHPUnit\TextUI\XmlConfiguration\TestSuiteMapper->map('C:\\Users\\prati\\...', Object(PHPUnit\TextUI\Configuration\TestSuiteCollection), '', '')
   #7 \vendor\phpunit\phpunit\src\TextUI\Application.php(349): PHPUnit\TextUI\Configuration\TestSuiteBuilder->build(Object(PHPUnit\TextUI\Configuration\Configuration))
   #8 \vendor\phpunit\phpunit\src\TextUI\Application.php(108): PHPUnit\TextUI\Application->buildTestSuite(Object(PHPUnit\TextUI\Configuration\Configuration))
   #9 \vendor\pestphp\pest\src\Kernel.php(103): PHPUnit\TextUI\Application->run(Array)
   #10 \vendor\pestphp\pest\bin\pest(91): Pest\Kernel->handle(Array, Array)
   #11 \vendor\pestphp\pest\bin\pest(99): {closure}()
   #12 {main}.
```
Please correct me if my implementation is wrong.

**Comment by netdelight** [comment]
Exact same problem here, and I'm new to Pest, so I'm not sure if the implementation is right.

**Comment by aalcala07** [comment]
I had this issue because v0.0.2 was installed by default. I used `composer require --dev spatie/pest-plugin-route-testing:^1.0` to install the latest version and that solved the problem.
